### PR TITLE
 crash bugfix and pyqt5 compatibility

### PR DESCRIPTION
**Pull request by herrkeuner**
Main changes for the crash bugfix:
- in the makethumbnail function the plotR object is thoroughly destroyed
after the figure is closed
- I changed the code block handed over when clicking the "Plot with"
button. Now the plot module is only imported again if there is no figure
active in matplotlib any more
- unwound some of the complexity of plotting-related imports and
function calls (got rid of pylab funtions as far as possible, moved
everything plot-related to the plot module, except for closing the
figure after thumbnail saving)

For pyqt5 compatibility:
- the available backend (pyqt4 or 5) is determined by trying to import
core modules from the respective backend, all imports and function calls
are then made accordingly

### CODE REVIEW

**Comment by wakass** [comment]
Why does the readme.md file diff read like there are no deletions. Surely the file existed before? Is there a versioning issue?

**Comment by wakass** [comment]
Also, plot.py seems to remove importing numpy while making use of it ferociously throughout. Has this been tested thoroughly?

**Comment by herrkeuner** [comment]
the numpy import is part of what the %pylab magic does. So no need to import it again. And yes, this has been tested pretty thoroughly. also directly plotting a datafile with the plot module works with a freshly started kernel.

**Comment by herrkeuner** [comment]
about the readme. mmmh, good question. I just changed it slightly for the python 3 compatibility update.

**Comment by wakass** [comment]
While it might still work, I still prefer explicit imports over implicit (2nd rule of the Zen of python). Both for future compatibility and clarity.

**Comment by herrkeuner** [comment]
okayyyy, I did as the wakass demanded. I also found the readme issue. I put it into the tessierplot module folder by accident...

**Pull request merged**
